- www/modules/contrib/project_browser_server/LICENSE.txt
- www/modules/contrib/project_browser_server/README.md
- www/modules/contrib/project_browser_server/example/pbs_example.info
- www/modules/contrib/project_browser_server/example/pbs_example.module
- www/modules/contrib/project_browser_server/project_browser_server.info
- www/modules/contrib/project_browser_server/project_browser_server.module
- www/modules/custom/borg_pbs/README.md
- www/modules/custom/borg_pbs/borg_pbs.info
- www/modules/custom/borg_pbs/borg_pbs.module
https://github.com/backdrop-ops/backdropcms.org/issues/73
> Issue #73: Add Browser Server to BackdropCMS.org

- www/themes/borg/css/components.css
Also added some alignment and accessiblity fixes (adding focus and active states to pager links)
> Fixed Page 1 on mobile pager missing the word Page

- www/modules/custom/borg_pbs/borg_pbs.module
https://github.com/backdrop-ops/backdropcms.org/issues/103
> Issue #103: Cleanup for borg_pbs

- www/modules/custom/borg_pbs/borg_pbs.module
Reverts backdrop-ops/backdropcms.org#104
> Revert "Issue #103: Cleanup for borg_pbs"

- www/modules/custom/borg_pbs/borg_pbs.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/103
> Fix stray semicolon

- www/modules/contrib/project/project.module
https://github.com/backdrop-ops/backdropcms.org/issues/102
> Issue #102: hook_node_load() uses wrong db condition for project query

- config/dev-active/views.view.modules.json
- www/themes/borg/css/project-search.css
This fixes #137 Allow users to search for modules with more than one word.
> Issue #137: Allow users to search multiple words on the /modules page.

- www/modules/custom/borg_pbs/borg_pbs.module
https://github.com/backdrop-ops/backdropcms.org/issues/141
> Issue 141: Update API terms to match core standard

- config/dev-active/layout.layout.own_profile.json
- config/dev-active/layout.layout.profile_edit.json
- www/themes/borg/css/base.css
- www/themes/borg/css/system.theme.css
- www/themes/borg/template.php
Reordered user form and shoved some fields in collapsible fieldsets
Added styles for prettiness
Also slipped in fix for Issue #144
> Issue #163: Clean up profile edit page

- www/modules/custom/borg_qa/gitlc.yml
Related to backdrop/backdrop#1413
> Add tests support via ZenCI.

- www/modules/custom/borg_cleanup/borg_cleanup.module
> Issue #272: Remove /node path from backdropcms.org.

- www/modules/custom/borg_pbs/borg_pbs.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/282.
> Issue #282: Switching project browser to using more verbose search instead of just node titles.

- www/modules/contrib/project/project_github/project_github.theme.inc
Reverts backdrop-ops/backdropcms.org#318
> Revert "Issue #317: Point documentation and issue queue links to the right pl…"

- config/dev-active/layout.layout.showcase.json
- config/live-active/layout.layout.showcase.json
Online PR, sorry for lame commit messages. Please squash and edit before merge ;)
> Issue #445, Wrong destination parameter for the "Add your own" link on the showcase page

- .lando.yml
- www/modules/custom/borg_project_metrics/borg_project_metrics.module
https://github.com/backdrop-ops/backdropcms.org/issues/544
> Issue #544: Fix project download counts.

- .lando.yml
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/645
> Issue #645: Update Drush to latest version.

- config/README.md
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/650
> Issue #650: Update config README.

- config/README.md
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/650
> Issue #650: Fix README formatting.

- config/staging/views.view.news.json
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/632
> Issue #632: Fix styling of RSS News feed.

- config/staging/antibot.settings.json
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/665
> Issue #665: Protect Tugboat demo sandbox form with Antibot.

- www/modules/custom/borg_mailers/borg_mailers_security/borg_mailers_security.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/670.
> Issue #670: Delay sending security emails until after node is saved.

- www/layouts/double_fixed_case/layout--double-fixed-case.tpl.php
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/615
> Issue #615: Fix header region on Showcase node pages for small screens.

- www/modules/custom/borg_tugboat/templates/tugboat-preview-create-page.tpl.php
- www/modules/custom/borg_tugboat/templates/tugboat-preview-ready-page.tpl.php
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/664
> Issue #664: Translate Tugboat template files.

- config/staging/views.view.providers.json
- config/staging/views.view.taxonomy_term.json
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/690
> Issue #690: Randomise views listings for more fairness.

- config/staging/views.view.providers.json
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/633
> Issue #633: Remove USA as default country for Service Provider views filters.

- config/staging/image.style.showcase_preview_512x512.json
- config/staging/views.view.showcase.json
- www/modules/contrib/image_max_size_crop/LICENSE.txt
- www/modules/contrib/image_max_size_crop/README.md
- www/modules/contrib/image_max_size_crop/image_max_size_crop.info
- www/modules/contrib/image_max_size_crop/image_max_size_crop.module
- www/themes/borg/css/components-views.css
- www/themes/borg/templates/views-view-fields--showcase--page.tpl.php
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/623
> Issue #623: Better styling of Showcase teasers.

- .tugboat/config.yml
- .tugboat/delete-comments.sh
- .tugboat/post-comment.sh
- .tugboat/reset-password.sh
- .tugboat/settings.local.php
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/621
> Issue #621: Use Tugboat for PR sandboxes.

- config/staging/layout.layout.showcase.json
- www/modules/custom/borg_project_metrics/borg_project_metrics.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/482
> Issue #482: Display Backdrop usage count in Showcase title.

- www/themes/borg/templates/node--project-search.tpl.php
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/794
> Issue #794: Watchdog log errors

- www/modules/custom/borg_profile/borg_profile.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/813.
> Issue 813: Warning: Invalid argument supplied for foreach() in dblog

- www/themes/borg/template.php
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/846.
> Fix cache bug in borg_project_has_wiki

- www/modules/custom/borg_github/borg_github.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/852
> Issue #852: Testing info file data

- .gitignore
- www/.gitignore
- www/civicrm.settings.php
Addresses https://github.com/backdrop-ops/backdropcms.org/issues/886.
> 886 beta civicrm settings

- www/modules/contrib/ip/LICENSE.txt
- www/modules/contrib/ip/README.md
- www/modules/contrib/ip/config/views.view.ip_tracker.json
- www/modules/contrib/ip/config/views.view.ip_tracker_user.json
- www/modules/contrib/ip/ip.drush.inc
- www/modules/contrib/ip/ip.info
- www/modules/contrib/ip/ip.install
- www/modules/contrib/ip/ip.module
- www/modules/contrib/ip/src/Plugin/views/argument/Ip2LongArgument.php
- www/modules/contrib/ip/src/Plugin/views/field/IpUserCountField.php
- www/modules/contrib/ip/src/Plugin/views/field/Long2IpField.php
- www/modules/contrib/ip/src/Plugin/views/filter/Ip2LongFilter.php
- www/modules/contrib/ip/views/ip.views.inc
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/822.
> Add IP Address Manager module

- www/modules/contrib/ban_ip/LICENSE.txt
- www/modules/contrib/ban_ip/README.md
- www/modules/contrib/ban_ip/ban_ip.info
- www/modules/contrib/ban_ip/ban_ip.install
- www/modules/contrib/ban_ip/ban_ip.module
- www/modules/contrib/ban_ip/ban_ip.test
- www/modules/contrib/ban_ip/ban_ip.tests.info
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/893.
> Issue #893: Add Ban IP module

- PATCHES.md
- www/modules/contrib/spambot/config/spambot.settings.json
- www/modules/contrib/spambot/spambot.admin.inc
- www/modules/contrib/spambot/spambot.install
- www/modules/contrib/spambot/spambot.module
Apply patch from https://github.com/backdrop-contrib/spambot/issues/4 and add to PATCHES.md.
> Patch spambot module

- www/modules/contrib/purge_users/LICENSE.txt
- www/modules/contrib/purge_users/README.md
- www/modules/contrib/purge_users/config/purge_users.settings.json
- www/modules/contrib/purge_users/css/purge_users.css
- www/modules/contrib/purge_users/purge_users.admin.inc
- www/modules/contrib/purge_users/purge_users.info
- www/modules/contrib/purge_users/purge_users.install
- www/modules/contrib/purge_users/purge_users.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/914.
> Issue 914: add Auto Purge Users module.

- www/modules/contrib/civicrm_cron/LICENSE.txt
- www/modules/contrib/civicrm_cron/README.md
- www/modules/contrib/civicrm_cron/civicrm_cron.info
- www/modules/contrib/civicrm_cron/civicrm_cron.install
- www/modules/contrib/civicrm_cron/civicrm_cron.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/906.
> Issue #906: Install CiviCRM Cron module on beta.backdropcms.org.

- www/modules/contrib/purge_users/purge_users.info
- www/modules/contrib/purge_users/purge_users.module
Update purge_users module to include a fix for a bug that was preventing purging on cron for blocked users.
> Update purge_users module to include latest bugfix.

- www/modules/custom/borg_civicrm/borg_civicrm.info
- www/modules/custom/borg_civicrm/borg_civicrm.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/927.
> Issue #927: Create borg_civicrm module to support Civi integration.

- www/themes/backdropcms/backdropcms.info
- www/themes/backdropcms/css/borg-civicrm.css
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/932.
> Issue #932: Add CSS file to theme to support CiviCRM integration.

- www/modules/contrib/purge_users/purge_users.info
- www/modules/contrib/purge_users/purge_users.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/936.
> Issue #936: Update purge_users module.

- www/modules/contrib/project/project_github/project_github.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/948
> Issue #948: Only respond to GitHub release 'published' event.

- www/modules/custom/borg_antispam/borg_antispam.info
- www/modules/custom/borg_antispam/borg_antispam.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/960.
> Issue #960: Create an antispam module specific for BackdropCMS.org.

- www/modules/custom/borg_profile/borg_profile.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/837.
> Issue #837: Fix bogus "projects I'm involved with" for short/simple user names

- www/modules/custom/borg_signup/borg_signup.info
- www/modules/custom/borg_signup/borg_signup.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/992.
> Issue #992: Create module that creates block for Newsletter signups.

- www/modules/custom/borg_signup/borg_signup.module
PR for https://github.com/backdrop-ops/backdropcms.org/issues/992
> Add actions div to signup form for easy centering of button.

- www/modules/custom/borg_signup/borg_signup.module
PR for https://github.com/backdrop-ops/backdropcms.org/issues/992
> Add GDPR checkbox to newsletter signup form.

- www/modules/custom/borg_signup/README.md
- www/modules/custom/borg_signup/borg_signup.install
- www/modules/custom/borg_signup/borg_signup.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/992.
> Add support for cross-site signup.

- www/modules/custom/borg_pbs/borg_pbs.module
Fixes #1014 
Maybe - I have no way to test.
> Remove extend PagerDefault

- www/modules/custom/borg_mailers/borg_mailers_security/borg_mailers_security.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/1013.
Also some code cleanup in affected functions.
> Issue #1013: Fix duplicate security emails.

- www/modules/custom/borg_mailers/borg_mailers_security/borg_mailers_security.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/1031.
> Issue #1031: Improve Security Advisory emails.

- www/modules/custom/borg_mailers/borg_mailers_security/borg_mailers_security.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/1033.
> Issue #1033: Fix security mailings query to respect email opt-out.

- www/themes/borg/css/node-showcase.css
Fixes #1047
Also added (what I hope) is better visual hierarchy for the title and subtitle.
Fixed white space issues in code
> Fix contrast issues on showcase header

- www/modules/custom/borg_cleanup/borg_cleanup.module
Fixes https://github.com/backdrop-ops/backdropcms.org/issues/1001.
> Issue #1001: Validate quote author if quote is given in external mention
